# Generated by Django 5.2.9 on 2025-12-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='items_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='meal_type',
            field=models.CharField(default='Other', max_length=20),
        ),
    ]
