# Generated by Django 5.2.9 on 2025-12-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='day_goal_achieved',
            field=models.BooleanField(default=False),
        ),
    ]
