# Generated by Django 5.2.9 on 2025-12-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_meallog_day_goal_achieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='running_calories',
            field=models.FloatField(default=0),
        ),
    ]
