# Generated by Django 5.2.9 on 2025-12-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=200, unique=True)),
                ('calories', models.FloatField(default=0.0)),
                ('protein_g', models.FloatField(default=0.0)),
                ('fat_g', models.FloatField(default=0.0)),
                ('carbs_g', models.FloatField(default=0.0)),
                ('fiber_g', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ingredient'],
            },
        ),
    ]
